// Generated by CoffeeScript 1.7.1
var DEBUG, FLAP, GAME_HEIGHT, GRAVITY, GROUND_HEIGHT, GROUND_Y, HEIGHT, OPENING, SCALE, SPAWN_RATE, SPEED, WIDTH, WebFontConfig, atualizarPontos, atualizarSaldo, bannerVisivel, bg, bird, carregarSaldo, deadInvs, deadTubeBottoms, deadTubeTops, fallSnd, flapSnd, floor, gameOver, gameOverText, gameStarted, generateLeaderboard, githubHtml, ground, hurtSnd, instText, invs, lastMsg, main, parent, pontosText, saldoAcumulado, saldoText, salvarSaldo, scheduleSocialProof, score, scoreSnd, scoreText, showHypeMessage, showNotification, swooshSnd, tentativasRestantes, tubes, tubesTimer, valorPorCano;

DEBUG = false;

SPEED = 160;

GRAVITY = 1100;

FLAP = 320;

SPAWN_RATE = 1 / 1200;

OPENING = 100;

SCALE = 1;

valorPorCano = 0.50;

saldoAcumulado = 0;

tentativasRestantes = 3;

bannerVisivel = true;

HEIGHT = 384;

WIDTH = 288;

GAME_HEIGHT = 336;

GROUND_HEIGHT = 64;

GROUND_Y = HEIGHT - GROUND_HEIGHT;

parent = document.querySelector("#screen");

gameStarted = void 0;

gameOver = void 0;

deadTubeTops = [];

deadTubeBottoms = [];

deadInvs = [];

bg = null;

tubes = null;

invs = null;

bird = null;

ground = null;

score = null;

scoreText = null;

instText = null;

gameOverText = null;

pontosText = null;

saldoText = null;

flapSnd = null;

scoreSnd = null;

hurtSnd = null;

fallSnd = null;

swooshSnd = null;

tubesTimer = null;

githubHtml = "<iframe src=\"http://ghbtns.com/github-btn.html?user=hyspace&repo=flappy&type=watch&count=true&size=large\"\nallowtransparency=\"true\" frameborder=\"0\" scrolling=\"0\" width=\"150\" height=\"30\"></iframe>";

floor = Math.floor;

atualizarSaldo = function() {
  if (saldoText) {
    return saldoText.setText("SALDO: R$ " + saldoAcumulado.toFixed(2));
  }
};

lastMsg = "";

showHypeMessage = function() {
  var container, el, msg, msgs;
  msgs = ["UAU!", "PARABÉNS!", "NOVO MILIONÁRIO!", "PIX CHEGANDO!", "RUMO AO MILHÃO!", "QUE JOGADA!", "TÁ CHOVENDO PIX!", "SÓ LUCRO!", "AULA DE FATURE!", "RECEBA!", "MAIS DINHEIRO!", "TOQUE DE MIDAS!", "SEGURA O PIX!", "FOGUETE NÃO TEM RÉ!", "DECOLOU!", "MESTRE DO PIX!", "PIX NO BOLSO!", "TÁ RICO!", "OLHA O GANHO!", "VAI QUE É TUA!"];
  while (true) {
    msg = msgs[Math.floor(Math.random() * msgs.length)];
    if (msg !== lastMsg) {
      break;
    }
  }
  lastMsg = msg;
  el = document.createElement("div");
  el.className = "hype-message";
  el.innerText = msg;
  el.style.top = (20 + Math.random() * 40) + "%";
  container = document.querySelector("#hype-container");
  container.appendChild(el);
  setTimeout(function() {
    return container.removeChild(el);
  }, 2000);
};

showNotification = function(icon, text) {
  var container, el;
  el = document.createElement("div");
  el.className = "social-proof-card";
  el.innerHTML = "" + icon + "<div class='social-content'>" + text + "</div>";
  container = document.querySelector("#notification-container");
  container.appendChild(el);
  setTimeout(function() {
    if (container.contains(el)) {
      return container.removeChild(el);
    }
  }, 4500);
};

scheduleSocialProof = function() {
  var colors, names, runSequence;
  names = ["Carlos H.", "Ana P.", "Eduardo M.", "Fernanda S.", "João V.", "Beatriz L.", "Lucas R.", "Mariana C.", "Gabriel O.", "Juliana K.", "Rafael T.", "Larissa B.", "Pedro G.", "Camila D.", "Gustavo N.", "Letícia F.", "Daniel S.", "Amanda W.", "Felipe J.", "Carolina M.", "Bruno A.", "Vanessa R.", "Thiago L.", "Bianca P.", "Rodrigo H.", "Jessica T.", "Leonardo C.", "Melissa G.", "Vinicius D.", "Gabriela S."];
  colors = ["#FFB7B2", "#B5EAD7", "#E2F0CB", "#FFDAC1", "#C7CEEA", "#F0E68C", "#D8BFD8", "#FF6961"];
  runSequence = function() {
    var avatarHtml, color, initial, joinPhrases, joinText, name, nextDelay, withdrawPhrases, withdrawText;
    name = names[Math.floor(Math.random() * names.length)];
    initial = name.charAt(0);
    color = colors[Math.floor(Math.random() * colors.length)];
    avatarHtml = "<div class='social-avatar' style='background-color: " + color + "; color: #333'>" + initial + "</div>";
    joinPhrases = ["entrou para o plano <span class='pro-badge'>PRO</span>", "agora faz parte do clube <span class='pro-badge'>PRO</span>", "acabou de assinar o <span class='pro-badge'>PRO</span>", "garantiu sua vaga no <span class='pro-badge'>PRO</span>", "começou a lucrar no <span class='pro-badge'>PRO</span>"];
    joinText = joinPhrases[Math.floor(Math.random() * joinPhrases.length)];
    withdrawPhrases = ["acabou de sacar", "recebeu um PIX de", "faturou agora", "retirou para a conta", "lucrou hoje"];
    withdrawText = withdrawPhrases[Math.floor(Math.random() * withdrawPhrases.length)];
    showNotification(avatarHtml, "<strong>" + name + "</strong> " + joinText);
    setTimeout(function() {
      var amount;
      amount = Math.floor(Math.random() * 400) + 150;
      return showNotification(avatarHtml, "<strong>" + name + "</strong> " + withdrawText + " <strong>R$ " + amount + ",00</strong>! UAU");
    }, 2000);
    nextDelay = Math.random() * 8000 + 5000;
    setTimeout(runSequence, nextDelay);
  };
  setTimeout(runSequence, 3000);
};

generateLeaderboard = function() {
  var container, html, i, name, names, rankClass, val, _i;
  names = ["Roberto M.", "Fernanda K.", "André L.", "Patrícia S.", "Marcos P."];
  container = document.querySelector("#leaderboard-container");
  html = "<div class='leaderboard-header'>🏆 TOP 5 DO DIA</div>";
  for (i = _i = 0; _i <= 4; i = ++_i) {
    name = names[i];
    val = 5000 - (i * 800) + Math.floor(Math.random() * 500);
    rankClass = "r-" + (i + 1);
    html += "<div class='leaderboard-item'>\n  <div class='rank " + rankClass + "'>" + (i + 1) + "</div>\n  <div class='player-name'>" + name + "</div>\n  <div class='player-value'>R$ " + val + ",00</div>\n</div>";
  }
  container.innerHTML = html;
};

generateLeaderboard();

scheduleSocialProof();

atualizarPontos = function() {
  if (pontosText) {
    return pontosText.setText("PONTOS: " + score);
  }
};

carregarSaldo = function() {
  var saldoSalvo;
  saldoSalvo = window.localStorage.getItem("saldoFlappyPix");
  return saldoAcumulado = saldoSalvo ? parseFloat(saldoSalvo) : 0;
};

salvarSaldo = function() {
  return window.localStorage.setItem("saldoFlappyPix", saldoAcumulado);
};

main = function() {
  var addScore, create, flap, game, preload, render, reset, setGameOver, spawntube, spawntubes, start, state, update;
  spawntube = function(openPos, flipped) {
    var tube, tubeKey, tubeY;
    tube = null;
    tubeKey = flipped ? "tubeTop" : "tubeBottom";
    if (flipped) {
      tubeY = floor(openPos - OPENING / 2 - 320);
    } else {
      tubeY = floor(openPos + OPENING / 2);
    }
    if (deadTubeTops.length > 0 && tubeKey === "tubeTop") {
      tube = deadTubeTops.pop().revive();
      tube.reset(game.world.width, tubeY);
    } else if (deadTubeBottoms.length > 0 && tubeKey === "tubeBottom") {
      tube = deadTubeBottoms.pop().revive();
      tube.reset(game.world.width, tubeY);
    } else {
      tube = tubes.create(game.world.width, tubeY, tubeKey);
      tube.body.allowGravity = false;
    }
    tube.body.velocity.x = -SPEED;
    return tube;
  };
  spawntubes = function() {
    var bottube, inv, toptube, tubeY;
    tubes.forEachAlive(function(tube) {
      if (tube.x + tube.width < game.world.bounds.left) {
        if (tube.key === "tubeTop") {
          deadTubeTops.push(tube.kill());
        }
        if (tube.key === "tubeBottom") {
          deadTubeBottoms.push(tube.kill());
        }
      }
    });
    invs.forEachAlive(function(invs) {
      if (invs.x + invs.width < game.world.bounds.left) {
        deadInvs.push(invs.kill());
      }
    });
    tubeY = game.world.height / 2 + (Math.random() - 0.5) * game.world.height * 0.2;
    bottube = spawntube(tubeY);
    toptube = spawntube(tubeY, true);
    if (deadInvs.length > 0) {
      inv = deadInvs.pop().revive().reset(toptube.x + toptube.width / 2, 0);
    } else {
      inv = invs.create(toptube.x + toptube.width / 2, 0);
      inv.width = 2;
      inv.height = game.world.height;
      inv.body.allowGravity = false;
    }
    inv.body.velocity.x = -SPEED;
  };
  addScore = function(_, inv) {
    invs.remove(inv);
    score += 1;
    scoreText.setText(score);
    scoreSnd.play();
    saldoAcumulado += valorPorCano;
    salvarSaldo();
    atualizarSaldo();
    atualizarPontos();
    showHypeMessage();
  };
  setGameOver = function() {
    var hiscore, msgTentativa;
    gameOver = true;
    if (bird.body.velocity.y > 0) {
      bird.body.velocity.y = 100;
    }
    bird.animations.stop();
    bird.frame = 1;
    tentativasRestantes -= 1;
    if (tentativasRestantes < 0) {
      tentativasRestantes = 0;
    }
    msgTentativa = tentativasRestantes > 0 ? "TOQUE\nPARA TENTAR NOVAMENTE\n(" + tentativasRestantes + " restam)" : "LIMITE ATINGIDO!\nVOLTE MAIS TARDE";
    instText.setText(msgTentativa);
    instText.renderable = true;
    hiscore = window.localStorage.getItem("hiscore");
    hiscore = (hiscore ? hiscore : score);
    hiscore = (score > parseInt(hiscore, 10) ? score : hiscore);
    window.localStorage.setItem("hiscore", hiscore);
    gameOverText.setText("GAME OVER\n\nRECORDE\n\n" + hiscore);
    gameOverText.renderable = true;
    tubes.forEachAlive(function(tube) {
      tube.body.velocity.x = 0;
    });
    invs.forEach(function(inv) {
      inv.body.velocity.x = 0;
    });
    game.time.events.remove(tubesTimer);
    game.time.events.add(1000, function() {
      return game.input.onTap.addOnce(function() {
        if (tentativasRestantes > 0) {
          reset();
          return swooshSnd.play();
        } else {
          return alert("Você atingiu o limite de 3 tentativas! Ganhe mais amanhã!");
        }
      });
    });
    hurtSnd.play();
  };
  flap = function() {
    var tween;
    if (!gameStarted) {
      start();
    }
    if (!gameOver) {
      bird.body.gravity.y = 0;
      bird.body.velocity.y = -100;
      tween = game.add.tween(bird.body.velocity).to({
        y: -FLAP
      }, 25, Phaser.Easing.Bounce.In, true);
      tween.onComplete.add(function() {
        return bird.body.gravity.y = GRAVITY;
      });
      flapSnd.play();
    }
  };
  preload = function() {
    var assets;
    assets = {
      spritesheet: {
        bird: ["assets/bird.png", 36, 26]
      },
      image: {
        tubeTop: ["assets/tube1.png"],
        tubeBottom: ["assets/tube2.png"],
        ground: ["assets/ground.png"],
        bg: ["assets/bg.png"]
      },
      audio: {
        flap: ["assets/sfx_wing.mp3"],
        score: ["assets/sfx_point.mp3"],
        hurt: ["assets/sfx_hit.mp3"],
        fall: ["assets/sfx_die.mp3"],
        swoosh: ["assets/sfx_swooshing.mp3"]
      }
    };
    Object.keys(assets).forEach(function(type) {
      Object.keys(assets[type]).forEach(function(id) {
        game.load[type].apply(game.load, [id].concat(assets[type][id]));
      });
    });
  };
  create = function() {
    var ratio;
    console.log("%chttps://github.com/hyspace/flappy", "color: black; font-size: x-large");
    ratio = window.innerWidth / window.innerHeight;
    if (ratio > 1.15 || ratio < 0.7) {
      document.querySelector('#github').innerHTML = githubHtml;
    }
    document.querySelector('#loading').style.display = 'none';
    carregarSaldo();
    window.gameInstance = {
      clickBanner: function() {
        bannerVisivel = false;
        console.log('🎮 Jogo: Banner marcado como invisível');
      }
    };
    if (window.bannerClicadoAntes) {
      bannerVisivel = false;
      document.querySelector('#banner-overlay').style.display = 'none';
    }
    Phaser.Canvas.setSmoothingEnabled(game.context, false);
    game.stage.scaleMode = Phaser.StageScaleMode.SHOW_ALL;
    game.stage.scale.setScreenSize(true);
    game.world.width = WIDTH;
    game.world.height = HEIGHT;
    bg = game.add.tileSprite(0, 0, WIDTH, HEIGHT, 'bg');
    tubes = game.add.group();
    invs = game.add.group();
    bird = game.add.sprite(0, 0, "bird");
    bird.anchor.setTo(0.5, 0.5);
    bird.animations.add("fly", [0, 1, 2], 10, true);
    bird.body.collideWorldBounds = true;
    bird.body.setPolygon(24, 1, 34, 16, 30, 32, 20, 24, 12, 34, 2, 12, 14, 2);
    ground = game.add.tileSprite(0, GROUND_Y, WIDTH, GROUND_HEIGHT, "ground");
    ground.tileScale.setTo(SCALE, SCALE);
    scoreText = game.add.text(game.world.width / 2, game.world.height / 4, "", {
      font: "16px \"Press Start 2P\"",
      fill: "#fff",
      stroke: "#430",
      strokeThickness: 4,
      align: "center"
    });
    scoreText.anchor.setTo(0.5, 0.5);
    pontosText = game.add.text(10, 10, "PONTOS: 0", {
      font: "8px \"Press Start 2P\"",
      fill: "#FFD700",
      stroke: "#000",
      strokeThickness: 2,
      align: "left"
    });
    pontosText.fixedToCamera = true;
    saldoText = game.add.text(10, 25, "SALDO: R$ 0,00", {
      font: "8px \"Press Start 2P\"",
      fill: "#00FF00",
      stroke: "#000",
      strokeThickness: 2,
      align: "left"
    });
    saldoText.fixedToCamera = true;
    atualizarSaldo();
    instText = game.add.text(game.world.width / 2, game.world.height - game.world.height / 4, "", {
      font: "8px \"Press Start 2P\"",
      fill: "#fff",
      stroke: "#430",
      strokeThickness: 4,
      align: "center"
    });
    instText.anchor.setTo(0.5, 0.5);
    gameOverText = game.add.text(game.world.width / 2, game.world.height / 2, "", {
      font: "16px \"Press Start 2P\"",
      fill: "#fff",
      stroke: "#430",
      strokeThickness: 4,
      align: "center"
    });
    gameOverText.anchor.setTo(0.5, 0.5);
    gameOverText.scale.setTo(SCALE, SCALE);
    flapSnd = game.add.audio("flap");
    scoreSnd = game.add.audio("score");
    hurtSnd = game.add.audio("hurt");
    fallSnd = game.add.audio("fall");
    swooshSnd = game.add.audio("swoosh");
    game.input.onDown.add(function() {
      if (!bannerVisivel) {
        flap();
      }
    });
    reset();
  };
  reset = function() {
    gameStarted = false;
    gameOver = false;
    score = 0;
    scoreText.setText("FLAPPY PIX");
    instText.setText("TOQUE\nPARA VOAR");
    gameOverText.renderable = false;
    bird.body.allowGravity = false;
    bird.reset(game.world.width * 0.3, game.world.height / 2);
    bird.angle = 0;
    bird.animations.play("fly");
    tubes.removeAll();
    invs.removeAll();
    atualizarPontos();
    atualizarSaldo();
  };
  start = function() {
    bird.body.allowGravity = true;
    bird.body.gravity.y = GRAVITY;
    tubesTimer = game.time.events.loop(1 / SPAWN_RATE, spawntubes);
    scoreText.setText(score);
    instText.renderable = false;
    gameStarted = true;
  };
  update = function() {
    var tween;
    if (gameStarted) {
      if (!gameOver) {
        bird.angle = (90 * (FLAP + bird.body.velocity.y) / FLAP) - 180;
        if (bird.angle < -30) {
          bird.angle = -30;
        }
        if (bird.angle > 80) {
          bird.angle = 90;
          bird.animations.stop();
          bird.frame = 1;
        } else {
          bird.animations.play();
        }
        game.physics.overlap(bird, tubes, function() {
          setGameOver();
          return fallSnd.play();
        });
        if (!gameOver && bird.body.bottom >= GROUND_Y) {
          setGameOver();
        }
        game.physics.overlap(bird, invs, addScore);
      } else {
        tween = game.add.tween(bird).to({
          angle: 90
        }, 100, Phaser.Easing.Bounce.Out, true);
        if (bird.body.bottom >= GROUND_Y + 3) {
          bird.y = GROUND_Y - 13;
          bird.body.velocity.y = 0;
          bird.body.allowGravity = false;
          bird.body.gravity.y = 0;
        }
      }
    } else {
      bird.y = (game.world.height / 2) + 8 * Math.cos(game.time.now / 200);
      bird.angle = 0;
    }
    if (!gameOver) {
      ground.tilePosition.x -= game.time.physicsElapsed * SPEED;
    }
  };
  render = function() {
    if (DEBUG) {
      game.debug.renderSpriteBody(bird);
      tubes.forEachAlive(function(tube) {
        game.debug.renderSpriteBody(tube);
      });
      invs.forEach(function(inv) {
        game.debug.renderSpriteBody(inv);
      });
    }
  };
  state = {
    preload: preload,
    create: create,
    update: update,
    render: render
  };
  game = new Phaser.Game(WIDTH, HEIGHT, Phaser.CANVAS, parent, state, false, false);
};

WebFontConfig = {
  google: {
    families: ['Press+Start+2P::latin']
  },
  active: main
};

(function() {
  var s, wf;
  wf = document.createElement('script');
  wf.src = ('https:' === document.location.protocol ? 'https' : 'http') + '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';
  s = document.getElementsByTagName('script')[0];
  return s.parentNode.insertBefore(wf, s);
})();
