// Generated by CoffeeScript 1.7.1
var DEBUG, FLAP, GAME_HEIGHT, GRAVITY, GROUND_HEIGHT, GROUND_Y, HEIGHT, OPENING, SCALE, SPAWN_RATE, SPEED, WIDTH, WebFontConfig, atualizarPontos, atualizarSaldo, bannerVisivel, bg, bird, carregarSaldo, comboStacks, deadInvs, deadTubeBottoms, deadTubeTops, fallSnd, flapSnd, floatingText, floor, gameOver, gameOverText, gameStarted, generateLeaderboard, ground, hurtSnd, instText, introSnd, invs, lastMsg, main, multiText, multiplicador, parent, pontosText, saldoAcumulado, saldoText, salvarSaldo, scheduleSocialProof, score, scoreSnd, scoreText, sessionEarnings, showHypeMessage, showNotification, survivalTimer, swooshSnd, taxaPorSegundo, tentativasRestantes, tubes, tubesTimer, valorPorCano, firstPlay;

DEBUG = false;

SPEED = 160;

GRAVITY = 1100;

FLAP = 320;

SPAWN_RATE = 1 / 1200;

OPENING = 120;

SCALE = 1;

valorPorCano = 10.00;

saldoAcumulado = 0;

taxaPorSegundo = 1.00;

multiplicador = 1.0;

survivalTimer = 0;

comboStacks = [];

sessionEarnings = 0;

floatingText = null;

multiText = null;

tentativasRestantes = 5;

bannerVisivel = true;

firstPlay = true;

HEIGHT = 384;

WIDTH = 288;

GAME_HEIGHT = 336;

GROUND_HEIGHT = 64;

GROUND_Y = HEIGHT - GROUND_HEIGHT;

parent = document.querySelector("#screen");

gameStarted = void 0;

gameOver = void 0;

deadTubeTops = [];

deadTubeBottoms = [];

deadInvs = [];

bg = null;

tubes = null;

invs = null;

bird = null;

ground = null;

score = null;

scoreText = null;

instText = null;

gameOverText = null;

pontosText = null;

saldoText = null;

flapSnd = null;

scoreSnd = null;

hurtSnd = null;

fallSnd = null;

swooshSnd = null;

introSnd = null;

tubesTimer = null;

floor = Math.floor;

atualizarSaldo = function () {
  if (saldoText) {
    return saldoText.setText("SALDO: R$ " + saldoAcumulado.toFixed(2));
  }
};

lastMsg = "";

showHypeMessage = function () {
  var container, el, msg, msgs;
  msgs = ["UAU!", "PARABÉNS!", "NOVO MILIONÁRIO!", "PIX CHEGANDO!", "RUMO AO MILHÃO!", "QUE JOGADA!", "TÁ CHOVENDO PIX!", "SÓ LUCRO!", "AULA DE FATURE!", "RECEBA!", "MAIS DINHEIRO!", "TOQUE DE MIDAS!", "SEGURA O PIX!", "FOGUETE NÃO TEM RÉ!", "DECOLOU!", "MESTRE DO PIX!", "PIX NO BOLSO!", "TÁ RICO!", "OLHA O GANHO!", "VAI QUE É TUA!"];
  while (true) {
    msg = msgs[Math.floor(Math.random() * msgs.length)];
    if (msg !== lastMsg) {
      break;
    }
  }
  lastMsg = msg;
  el = document.createElement("div");
  el.className = "hype-message";
  el.innerText = msg;
  el.style.top = (20 + Math.random() * 40) + "%";
  container = document.querySelector("#hype-container");
  container.appendChild(el);
  setTimeout(function () {
    return container.removeChild(el);
  }, 2000);
};

showNotification = function (icon, text) {
  var container, el;
  el = document.createElement("div");
  el.className = "social-proof-card";
  el.innerHTML = "" + icon + "<div class='social-content'>" + text + "</div>";
  container = document.querySelector("#notification-container");
  container.appendChild(el);
  setTimeout(function () {
    if (container.contains(el)) {
      return container.removeChild(el);
    }
  }, 4500);
};

scheduleSocialProof = function () {
  var colors, names, runSequence;
  names = ["Carlos H.", "Ana P.", "Eduardo M.", "Fernanda S.", "João V.", "Beatriz L.", "Lucas R.", "Mariana C.", "Gabriel O.", "Juliana K.", "Rafael T.", "Larissa B.", "Pedro G.", "Camila D.", "Gustavo N.", "Letícia F.", "Daniel S.", "Amanda W.", "Felipe J.", "Carolina M.", "Bruno A.", "Vanessa R.", "Thiago L.", "Bianca P.", "Rodrigo H.", "Jessica T.", "Leonardo C.", "Melissa G.", "Vinicius D.", "Gabriela S."];
  colors = ["#FFB7B2", "#B5EAD7", "#E2F0CB", "#FFDAC1", "#C7CEEA", "#F0E68C", "#D8BFD8", "#FF6961"];
  runSequence = function () {
    var avatarHtml, color, initial, joinPhrases, joinText, name, nextDelay, withdrawPhrases, withdrawText;
    name = names[Math.floor(Math.random() * names.length)];
    initial = name.charAt(0);
    color = colors[Math.floor(Math.random() * colors.length)];
    avatarHtml = "<div class='social-avatar' style='background-color: " + color + "; color: #333'>" + initial + "</div>";
    joinPhrases = ["entrou para o plano <span class='pro-badge'>PRO</span>", "agora faz parte do clube <span class='pro-badge'>PRO</span>", "acabou de assinar o <span class='pro-badge'>PRO</span>", "garantiu sua vaga no <span class='pro-badge'>PRO</span>", "começou a lucrar no <span class='pro-badge'>PRO</span>"];
    joinText = joinPhrases[Math.floor(Math.random() * joinPhrases.length)];
    withdrawPhrases = ["acabou de sacar", "recebeu um PIX de", "faturou agora", "retirou para a conta", "lucrou hoje"];
    withdrawText = withdrawPhrases[Math.floor(Math.random() * withdrawPhrases.length)];
    showNotification(avatarHtml, "<strong>" + name + "</strong> " + joinText);
    setTimeout(function () {
      var amount;
      amount = Math.floor(Math.random() * 400) + 150;
      return showNotification(avatarHtml, "<strong>" + name + "</strong> " + withdrawText + " <strong>R$ " + amount + ",00</strong>! UAU");
    }, 2000);
    nextDelay = Math.random() * 8000 + 5000;
    setTimeout(runSequence, nextDelay);
  };
  setTimeout(runSequence, 3000);
};

generateLeaderboard = function () {
  var collapseTimeout, container, html, i, name, names, rankClass, startAutoCollapse, updateHeader, val, _i;
  names = ["Roberto M.", "Fernanda K.", "André L.", "Patrícia S.", "Marcos P."];
  container = document.querySelector("#leaderboard-container");
  updateHeader = function () {
    var header;
    header = container.querySelector('.leaderboard-header');
    if (container.classList.contains("expanded")) {
      return header.innerText = "🏆 TOP 5 PIX DO DIA";
    } else {
      return header.innerText = "🏆 TOP 5";
    }
  };
  collapseTimeout = null;
  startAutoCollapse = function () {
    if (collapseTimeout) {
      clearTimeout(collapseTimeout);
    }
    return collapseTimeout = setTimeout(function () {
      if (container.classList.contains("expanded")) {
        container.classList.remove("expanded");
        return updateHeader();
      }
    }, 5000);
  };
  container.addEventListener("click", function () {
    container.classList.toggle("expanded");
    updateHeader();
    if (container.classList.contains("expanded")) {
      return startAutoCollapse();
    }
  });
  window.expandLeaderboard = function () {
    if (!container.classList.contains("expanded")) {
      container.classList.add("expanded");
      updateHeader();
      return startAutoCollapse();
    }
  };
  html = "<div class='leaderboard-header'>🏆 TOP 5</div>\n<div class='leaderboard-content'>";
  for (i = _i = 0; _i <= 4; i = ++_i) {
    name = names[i];
    val = 5000 - (i * 800) + Math.floor(Math.random() * 500);
    rankClass = "r-" + (i + 1);
    html += "<div class='leaderboard-item'>\n  <div class='rank " + rankClass + "'>" + (i + 1) + "</div>\n  <div class='player-name'>" + name + "</div>\n  <div class='player-value'>R$ " + val + ",00</div>\n</div>";
  }
  html += "</div>";
  container.innerHTML = html;
};

generateLeaderboard();

atualizarPontos = function () {
  if (pontosText) {
    return pontosText.setText("PONTOS: " + score);
  }
};

carregarSaldo = function () {
  saldoAcumulado = 0;
  return salvarSaldo();
};

salvarSaldo = function () {
  return window.localStorage.setItem("saldoFlappyPix", saldoAcumulado);
};

main = function () {
  var addScore, create, flap, game, preload, render, reset, setGameOver, spawntube, spawntubes, start, state, update;
  spawntube = function (openPos, flipped) {
    var tube, tubeKey, tubeY;
    tube = null;
    tubeKey = flipped ? "tubeTop" : "tubeBottom";
    if (flipped) {
      tubeY = floor(openPos - OPENING / 2 - 320);
    } else {
      tubeY = floor(openPos + OPENING / 2);
    }
    if (deadTubeTops.length > 0 && tubeKey === "tubeTop") {
      tube = deadTubeTops.pop().revive();
      tube.reset(game.world.width, tubeY);
    } else if (deadTubeBottoms.length > 0 && tubeKey === "tubeBottom") {
      tube = deadTubeBottoms.pop().revive();
      tube.reset(game.world.width, tubeY);
    } else {
      tube = tubes.create(game.world.width, tubeY, tubeKey);
      tube.body.allowGravity = false;
    }
    tube.body.velocity.x = -SPEED;
    return tube;
  };
  spawntubes = function () {
    var bottube, inv, toptube, tubeY;
    tubes.forEachAlive(function (tube) {
      if (tube.x + tube.width < game.world.bounds.left) {
        if (tube.key === "tubeTop") {
          deadTubeTops.push(tube.kill());
        }
        if (tube.key === "tubeBottom") {
          deadTubeBottoms.push(tube.kill());
        }
      }
    });
    invs.forEachAlive(function (invs) {
      if (invs.x + invs.width < game.world.bounds.left) {
        deadInvs.push(invs.kill());
      }
    });
    tubeY = game.world.height / 2 + (Math.random() - 0.5) * game.world.height * 0.2;
    bottube = spawntube(tubeY);
    toptube = spawntube(tubeY, true);
    if (deadInvs.length > 0) {
      inv = deadInvs.pop().revive().reset(toptube.x + toptube.width / 2, 0);
    } else {
      inv = invs.create(toptube.x + toptube.width / 2, 0);
      inv.width = 2;
      inv.height = game.world.height;
      inv.body.allowGravity = false;
    }
    inv.body.velocity.x = -SPEED;
  };
  addScore = function (_, inv) {
    var comboFly, comboVal, currentMulti, survivalBonus;
    invs.remove(inv);
    score += 1;
    scoreText.setText(score);
    scoreSnd.play();
    comboStacks.push(game.time.now);
    survivalBonus = Math.floor(survivalTimer / 5) * 1.0;
    currentMulti = 1.0 + survivalBonus + comboStacks.length * 0.5;
    if (currentMulti > 4.0) {
      currentMulti = 4.0;
    }
    comboVal = currentMulti.toFixed(1);
    comboFly = game.add.text(bird.x, bird.y - 20, "COMBO " + comboVal + "x!", {
      font: "10px 'Press Start 2P'",
      fill: "#FFD700",
      stroke: "#000",
      strokeThickness: 3
    });
    game.add.tween(comboFly).to({
      y: bird.y - 60,
      alpha: 0
    }, 800, Phaser.Easing.Linear.None, true).onComplete.add(function () {
      return comboFly.destroy();
    });
    showHypeMessage();
  };
  setGameOver = function () {
    var hiscore, msgTentativa;
    gameOver = true;
    salvarSaldo();
    if (bird.body.velocity.y > 0) {
      bird.body.velocity.y = 100;
    }
    bird.animations.stop();
    bird.frame = 1;
    tentativasRestantes -= 1;
    if (tentativasRestantes < 0) {
      tentativasRestantes = 0;
    }
    msgTentativa = tentativasRestantes > 0 ? "TOQUE\nPARA TENTAR NOVAMENTE\n(" + tentativasRestantes + " restam)" : "LIMITE ATINGIDO!\nVOLTE MAIS TARDE";
    instText.setText(msgTentativa);
    instText.renderable = true;
    hiscore = window.localStorage.getItem("hiscore");
    hiscore = (hiscore ? hiscore : score);
    hiscore = (score > parseInt(hiscore, 10) ? score : hiscore);
    window.localStorage.setItem("hiscore", hiscore);
    gameOverText.setText("GAME OVER\n\nRECORDE\n\n" + hiscore);
    gameOverText.renderable = true;
    tubes.forEachAlive(function (tube) {
      tube.body.velocity.x = 0;
    });
    invs.forEach(function (inv) {
      inv.body.velocity.x = 0;
    });
    game.time.events.remove(tubesTimer);
    game.time.events.add(1000, function () {
      return game.input.onTap.addOnce(function () {
        var triggerVictory = function () {
          // 0. Clean up Phaser Text
          if (gameOverText) gameOverText.renderable = false;
          if (instText) instText.renderable = false;
          if (scoreText) scoreText.renderable = false;

          // 1. Play Victory Sound (using score sound for joy)
          scoreSnd.play();

          // 2. Confetti Effect (More particles + sway)
          for (var i = 0; i < 150; i++) {
            var confetti = document.createElement('div');
            confetti.className = 'confetti';
            confetti.style.left = Math.random() * 100 + 'vw';
            // Random delay so they don't all start at once
            confetti.style.animation = 'confetti-fall ' + (Math.random() * 3 + 2) + 's linear forwards';
            confetti.style.animationDelay = (Math.random() * 2) + 's';

            // Random colors (Vibrant Palette)
            var colors = ['#FFD700', '#FF0000', '#00FF00', '#0000FF', '#FF00FF', '#00FFFF', '#FFA500'];
            confetti.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)];

            // Random shapes (Circle or Square)
            if (Math.random() > 0.5) {
              confetti.style.borderRadius = '50%';
            }

            document.body.appendChild(confetti);

            // Cleanup
            setTimeout(function (el) { return function () { if (el.parentNode) el.parentNode.removeChild(el); }; }(confetti), 6000);
          }

          // 3. Show Victory Overlay
          var overlay = document.getElementById('victory-overlay');
          var vAmount = document.getElementById('victory-amount-display');
          if (overlay && vAmount) {
            vAmount.innerText = "R$ " + saldoAcumulado.toFixed(2).replace('.', ',');
            overlay.classList.add('active');
          }

          // 4. Transition to Withdrawal Modal after 2.5s
          setTimeout(function () {
            if (overlay) overlay.classList.remove('active');

            var modal = document.getElementById('withdrawal-modal');
            if (modal) {
              var amountEl = document.getElementById('modal-balance-display');
              if (amountEl) {
                amountEl.innerText = "R$ " + saldoAcumulado.toFixed(2).replace('.', ',');
              }
              modal.classList.add('visible'); // Use class for animation
              console.log('💰 Modal de Saque (Mock) Exibido com Animação!');
            }
          }, 2500);
        };

        if (tentativasRestantes > 0) {
          reset();
          return swooshSnd.play();
        } else {
          triggerVictory();
          return game.input.onTap.removeAll();
        }
      });
    });
    hurtSnd.play();
  };
  flap = function () {
    var tween;
    if (!gameStarted) {
      start();
    }
    if (!gameOver) {
      bird.body.gravity.y = 0;
      bird.body.velocity.y = -100;
      tween = game.add.tween(bird.body.velocity).to({
        y: -FLAP
      }, 25, Phaser.Easing.Bounce.In, true);
      tween.onComplete.add(function () {
        return bird.body.gravity.y = GRAVITY;
      });
      flapSnd.play();
    }
  };
  preload = function () {
    var assets;
    assets = {
      spritesheet: {
        bird: ["assets/bird.png", 36, 26]
      },
      image: {
        tubeTop: ["assets/tube1.png"],
        tubeBottom: ["assets/tube2.png"],
        ground: ["assets/ground.png"],
        bg: ["assets/bg.png"]
      },
      audio: {
        flap: ["assets/sfx_wing.mp3"],
        score: ["assets/sfx_point.mp3"],
        hurt: ["assets/sfx_hit.mp3"],
        fall: ["assets/sfx_die.mp3"],
        swoosh: ["assets/sfx_swooshing.mp3"],
        intro: ["assets/bom-dia-magnata.mp3"]
      }
    };
    Object.keys(assets).forEach(function (type) {
      Object.keys(assets[type]).forEach(function (id) {
        game.load[type].apply(game.load, [id].concat(assets[type][id]));
      });
    });
  };
  create = function () {
    var ratio;
    console.log("%cFLAPPY PIX", "color: #00E676; font-size: x-large");
    ratio = window.innerWidth / window.innerHeight;
    document.querySelector('#loading').style.display = 'none';
    window.gameInstance = {
      clickBanner: function () {
        bannerVisivel = false;
        document.getElementById('banner-overlay').style.display = 'none';
        console.log('🎮 Jogo: Banner marcado como invisível');
      }
    };
    if (window.bannerClicadoAntes) {
      bannerVisivel = false;
      document.querySelector('#banner-overlay').style.display = 'none';
    }
    Phaser.Canvas.setSmoothingEnabled(game.context, false);
    game.stage.scaleMode = Phaser.StageScaleMode.SHOW_ALL;
    game.stage.scale.setScreenSize(true);
    game.world.width = WIDTH;
    game.world.height = HEIGHT;
    bg = game.add.tileSprite(0, 0, WIDTH, HEIGHT, 'bg');
    tubes = game.add.group();
    invs = game.add.group();
    bird = game.add.sprite(0, 0, "bird");
    bird.anchor.setTo(0.5, 0.5);
    bird.animations.add("fly", [0, 1, 2], 10, true);
    bird.body.collideWorldBounds = true;
    bird.body.setPolygon(24, 1, 34, 16, 30, 32, 20, 24, 12, 34, 2, 12, 14, 2);
    ground = game.add.tileSprite(0, GROUND_Y, WIDTH, GROUND_HEIGHT, "ground");
    ground.tileScale.setTo(SCALE, SCALE);
    scoreText = game.add.text(game.world.width / 2, game.world.height / 4, "", {
      font: "16px \"Press Start 2P\"",
      fill: "#fff",
      stroke: "#430",
      strokeThickness: 4,
      align: "center"
    });
    scoreText.anchor.setTo(0.5, 0.5);
    pontosText = game.add.text(10, 10, "PONTOS: 0", {
      font: "8px \"Press Start 2P\"",
      fill: "#FFD700",
      stroke: "#000",
      strokeThickness: 2,
      align: "left"
    });
    pontosText.fixedToCamera = true;
    saldoText = game.add.text(10, 25, "SALDO: R$ 0,00", {
      font: "8px \"Press Start 2P\"",
      fill: "#00FF00",
      stroke: "#000",
      strokeThickness: 2,
      align: "left"
    });
    saldoText.fixedToCamera = true;
    multiText = game.add.text(10, 40, "MULT: 1.0x (R$1.00/s)", {
      font: "8px \"Press Start 2P\"",
      fill: "#FFFFFF",
      stroke: "#000",
      strokeThickness: 2
    });
    multiText.fixedToCamera = true;
    atualizarSaldo();
    floatingText = game.add.text(0, 0, "+R$ 0,00", {
      font: "10px \"Press Start 2P\"",
      fill: "#00FF00",
      stroke: "#000",
      strokeThickness: 3,
      align: "center"
    });
    floatingText.anchor.setTo(0.5, 0.5);
    floatingText.alpha = 0;
    instText = game.add.text(game.world.width / 2, game.world.height - game.world.height / 4, "", {
      font: "8px \"Press Start 2P\"",
      fill: "#fff",
      stroke: "#430",
      strokeThickness: 4,
      align: "center"
    });
    instText.anchor.setTo(0.5, 0.5);
    gameOverText = game.add.text(game.world.width / 2, game.world.height / 2, "", {
      font: "16px \"Press Start 2P\"",
      fill: "#fff",
      stroke: "#430",
      strokeThickness: 4,
      align: "center"
    });
    gameOverText.anchor.setTo(0.5, 0.5);
    gameOverText.scale.setTo(SCALE, SCALE);
    flapSnd = game.add.audio("flap");
    scoreSnd = game.add.audio("score");
    hurtSnd = game.add.audio("hurt");
    fallSnd = game.add.audio("fall");
    swooshSnd = game.add.audio("swoosh");
    introSnd = game.add.audio("intro");
    game.input.onDown.add(function () {
      if (!bannerVisivel) {
        flap();
      }
    });
    reset();
  };
  reset = function () {
    gameStarted = false;
    gameOver = false;
    score = 0;
    scoreText.setText("FLAPPY PIX");
    instText.setText("TOQUE\nPARA VOAR");
    gameOverText.renderable = false;
    bird.body.allowGravity = false;
    bird.reset(game.world.width * 0.3, game.world.height / 2);
    bird.angle = 0;
    bird.animations.play("fly");
    tubes.removeAll();
    invs.removeAll();
    multiplicador = 1.0;
    survivalTimer = 0;
    comboStacks = [];
    sessionEarnings = 0;
    if (multiText) {
      multiText.setText("MULT: 1.0x (R$1.00/s)");
    }
    if (saldoText) {
      saldoText.fill = "#00FF00";
    }
    atualizarPontos();
    atualizarSaldo();
  };
  start = function () {
    bird.body.allowGravity = true;
    bird.body.gravity.y = GRAVITY;
    tubesTimer = game.time.events.loop(1 / SPAWN_RATE, spawntubes);
    scoreText.setText(score);
    instText.renderable = false;
    gameStarted = true;
    if (typeof window.expandLeaderboard === 'function') {
      window.expandLeaderboard();
    }
    if (firstPlay) {
      if (introSnd) {
        introSnd.play();
      }
      firstPlay = false;
    }
  };
  update = function () {
    var comboBonus, dt, earningPerSec, gain, now, s, s2, scaleVal, survivalBonus, tween;
    if (gameStarted) {
      if (!gameOver) {
        bird.angle = (90 * (FLAP + bird.body.velocity.y) / FLAP) - 180;
        if (bird.angle < -30) {
          bird.angle = -30;
        }
        if (bird.angle > 80) {
          bird.angle = 90;
          bird.animations.stop();
          bird.frame = 1;
        } else {
          bird.animations.play();
        }
        game.physics.overlap(bird, tubes, function () {
          setGameOver();
          return fallSnd.play();
        });
        if (!gameOver && bird.body.bottom >= GROUND_Y) {
          setGameOver();
        }
        game.physics.overlap(bird, invs, addScore);
        dt = game.time.physicsElapsed;
        survivalTimer += dt;
        now = game.time.now;
        comboStacks = comboStacks.filter(function (time) {
          return now - time < 5000;
        });
        survivalBonus = Math.floor(survivalTimer / 5) * 1.0;
        comboBonus = comboStacks.length * 0.5;
        multiplicador = 1.0 + survivalBonus + comboBonus;
        if (multiplicador > 4.0) {
          multiplicador = 4.0;
        }
        if (multiText) {
          earningPerSec = (taxaPorSegundo * multiplicador).toFixed(2);
          multiText.setText("MULT: " + multiplicador.toFixed(1) + ("x (R$" + earningPerSec + "/s)"));
          if (multiplicador > 1.0) {
            multiText.fill = "#FFD700";
            s = 1 + Math.sin(now / 150) * 0.1;
            multiText.scale.setTo(s, s);
          }
        } else {
          multiText.fill = "#FFFFFF";
          multiText.scale.setTo(1, 1);
        }
        gain = (taxaPorSegundo * multiplicador) * dt;
        saldoAcumulado += gain;
        sessionEarnings += gain;
        if (multiplicador >= 2.0) {
          if (saldoText) {
            saldoText.fill = "#FFD700";
            s2 = 1 + Math.sin(now / 100) * 0.1;
            saldoText.scale.setTo(s2, s2);
          }
        } else {
          if (saldoText) {
            saldoText.fill = "#00FF00";
            saldoText.scale.setTo(1, 1);
          }
        }
        if (saldoText) {
          saldoText.setText("SALDO: R$ " + saldoAcumulado.toFixed(2));
        }
        if (floatingText) {
          floatingText.x = bird.x;
          floatingText.y = bird.y + 40;
          floatingText.setText("+R$ " + sessionEarnings.toFixed(2));
          floatingText.alpha = 1;
          scaleVal = 1 + Math.sin(game.time.now / 100) * 0.1;
          floatingText.scale.setTo(scaleVal, scaleVal);
        }
      } else {
        tween = game.add.tween(bird).to({
          angle: 90
        }, 100, Phaser.Easing.Bounce.Out, true);
        if (bird.body.bottom >= GROUND_Y + 3) {
          bird.y = GROUND_Y - 13;
          bird.body.velocity.y = 0;
          bird.body.allowGravity = false;
          bird.body.gravity.y = 0;
        }
      }
    } else {
      bird.y = (game.world.height / 2) + 8 * Math.cos(game.time.now / 200);
      bird.angle = 0;
    }
    if (!gameOver) {
      ground.tilePosition.x -= game.time.physicsElapsed * SPEED;
    }
  };
  render = function () {
    if (DEBUG) {
      game.debug.renderSpriteBody(bird);
      tubes.forEachAlive(function (tube) {
        game.debug.renderSpriteBody(tube);
      });
      invs.forEach(function (inv) {
        game.debug.renderSpriteBody(inv);
      });
    }
  };
  state = {
    preload: preload,
    create: create,
    update: update,
    render: render
  };
  game = new Phaser.Game(WIDTH, HEIGHT, Phaser.CANVAS, parent, state, false, false);
};

WebFontConfig = {
  google: {
    families: ['Press+Start+2P::latin']
  },
  active: main
};

(function () {
  var s, wf;
  wf = document.createElement('script');
  wf.src = ('https:' === document.location.protocol ? 'https' : 'http') + '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
  wf.type = 'text/javascript';
  wf.async = 'true';
  s = document.getElementsByTagName('script')[0];
  return s.parentNode.insertBefore(wf, s);
})();
